---
- name: Use gcs_backend role to set up gcs bucket with versioning enabled for TF remote backend
  hosts: all
  gather_facts: true
  vars:
    project_name: ""
    bucket_name: ""
  tasks:
    - name: Create a gcs bucket for Terraform remote backend
      ansible.builtin.include_role:
        name: cloud.terraform_ops.gcs_backend
      vars:
        gcs_backend_operation: create
        gcs_backend_bucket_name: "{{ bucket_name }}"
        gcs_backend_gcp_project: "{{ project_name }}"
        gcs_backend_auth_kind: serviceaccount
